### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by atinux** [Intevel/nuxt-logsnag#1]
- [x] Update README to mention that they can simply add `LOGSNAG_API_TOKEN` environment in `.env` instead of setting in `nuxt.config`
- [x] Is the API token for log snag public? 🤔 
- [x] Is it necessary? https://github.com/Intevel/nuxt-logsnag/blob/master/src/runtime/plugin.ts#L4
- [x] I would rename it to `publish` on https://github.com/Intevel/nuxt-logsnag/blob/master/src/runtime/composables/useLogSnag.ts#L26, like the npm module: https://www.npmjs.com/package/logsnag
- [x] Rename `#app` to `#imports` on https://github.com/Intevel/nuxt-logsnag/blob/master/src/runtime/composables/useLogSnag.ts#L2

**Comment by Intevel** [comment]
Hey @Atinux, thanks. 
Improved your suggestions in the newest release. 💚
